### ISSUE TITLE
Installation using pip on Windows fails; but conda works

### ISSUE THREAD

**Issue by haesleinhuepf** [AllenCellModeling/napari-aicsimageio#47]
## Description
The command 'pip install napari-aicsimageio' fails on plain Windows, because no build-tools are installed. However, `conda install napari-aicsimageio -c conda-forge` works. Thus, I'm just wondering if it might make sense to point this out in the [installation instructions](https://github.com/AllenCellModeling/napari-aicsimageio#installation)

## Expected Behavior

The installation instructions could propose this to install the plugin:

```
conda install napari-aicsimageio -c conda-forge
```

## Reproduction
*A minimal example that exhibits the behavior.*

## Environment
*Any additional information about your environment*

A pretty new Windows computer, with pretty much nothing installed.

**Comment by JacksonMaxfield** [comment]
Curious what the pip install failure. I would like to leave pip install but would happily accept a "or install with conda" PR

**Comment by JacksonMaxfield** [comment]
Also interesting that the conda install works because uhhhhh I think the conda release of napari-aicsimageio is very old.... we haven't gotten any releases out because of build dependencies: https://github.com/conda-forge/napari-aicsimageio-feedstock/pull/4

**Comment by psobolewskiPhD** [comment]
All 3 of those packages are on conda-forge...
But that doesn't help with the pip issue.
In a fresh conda env with napari (from conda), `pip install napari-aicsimageio --no-cache-dir` yields a buncha wheels, but also:
`Building wheels for collected packages: lxml, jpype1, imageio-ffmpeg`
So those 3 obv. require build tools on arm64, but they all seem to have wheels for windows?

**Comment by PanosOik** [comment]
> Curious what the pip install failure. 

This is the error message I saw with @haesleinhuepf 

```
  × Running setup.py install for numcodecs did not run successfully.
  │ exit code: 1
  ╰─> [124 lines of output]
      [numcodecs] setting up Blosc extension
      [numcodecs] compiling Blosc extension with SSE2 support
      [numcodecs] compiling Blosc extension with AVX2 support
      [numcodecs] setting up Zstandard extension
      [numcodecs] setting up LZ4 extension
      [numcodecs] setting up compat extension
      [numcodecs] setting up shuffle extension
      [numcodecs] setting up vlen extension
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\abc.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\astype.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\base64.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\bz2.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\categorize.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\checksum32.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\compat.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\delta.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\fixedscaleoffset.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\gzip.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\json.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\lzma.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\msgpacks.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\packbits.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\pickles.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\quantize.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\registry.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\shuffle.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\version.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\zfpy.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\zlib.py -> build\lib.win-amd64-3.10\numcodecs
      copying .\numcodecs\__init__.py -> build\lib.win-amd64-3.10\numcodecs
      creating build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\common.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_astype.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_base64.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_blosc.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_bz2.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_categorize.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_checksum32.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_compat.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_delta.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_fixedscaleoffset.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_gzip.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_json.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_lz4.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_lzma.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_msgpacks.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_packbits.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_pickles.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_quantize.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_registry.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_shuffle.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_vlen_array.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_vlen_bytes.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_vlen_utf8.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_zfpy.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_zlib.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\test_zstd.py -> build\lib.win-amd64-3.10\numcodecs\tests
      copying .\numcodecs\tests\__init__.py -> build\lib.win-amd64-3.10\numcodecs\tests
      running build_ext
      building 'numcodecs.blosc' extension
      [numcodecs] Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      Traceback (most recent call last):
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-rptzegif\numcodecs_3c15dd6355c2460385a35e08833e6de7\setup.py", line 301, in build_extension
          build_ext.build_extension(self, ext)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\command\build_ext.py", line 529, in build_extension
          objects = self.compiler.compile(sources,
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\_msvccompiler.py", line 323, in compile
          self.initialize()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\_msvccompiler.py", line 220, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Users\Administrator\napari_env\lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "C:\Users\Administrator\napari_env\lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-rptzegif\numcodecs_3c15dd6355c2460385a35e08833e6de7\setup.py", line 377, in <module>
          run_setup(with_extensions)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-rptzegif\numcodecs_3c15dd6355c2460385a35e08833e6de7\setup.py", line 326, in run_setup
          setup(
        File "C:\Users\Administrator\napari_env\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\napari_env\lib\site-packages\setuptools\command\install.py", line 61, in run
          return orig.install.run(self)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\command\install.py", line 568, in run
          self.run_command('build')
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-rptzegif\numcodecs_3c15dd6355c2460385a35e08833e6de7\setup.py", line 294, in run
          build_ext.run(self)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\command\build_ext.py", line 340, in run
          self.build_extensions()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\command\build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-rptzegif\numcodecs_3c15dd6355c2460385a35e08833e6de7\setup.py", line 304, in build_extension
          raise BuildFailed()
      __main__.BuildFailed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> numcodecs

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by JacksonMaxfield** [comment]
This is a numcodecs install error not an aicsimageio install error. I think we can transfer the issue

Before I transfer can you give us the python version pip version and windows version you are on?

**Comment by psobolewskiPhD** [comment]
Winner winner chicken diner.
There arn't any Python 3.10 wheels for `numcodecs`
https://pypi.org/project/numcodecs/#files
Try a python 3.9 env.

**Comment by PanosOik** [comment]
Installed today Python 3.9, Windows 10

**Comment by psobolewskiPhD** [comment]
> Installed today Python 3.9, Windows 10

The error:
```
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\numcodecs
```
Indicates python 3.10...
Are you sure it was 3.9? 3.9 has wheels (pre-compiled binaries) pn pypi.

**Comment by PanosOik** [comment]
> try `python --version` in your conda env
Python 3.9.12

**Comment by psobolewskiPhD** [comment]
👀 
Very odd. There are 3.9 wheels available and the message says 3.10 wheels were being built...
🤷‍♂️

**Comment by JacksonMaxfield** [comment]
I guess I will transfer the issue?

**Comment by JacksonMaxfield** [comment]
Closing in favor of the newly created numcodecs issue. Please move to that thread.

**Comment by JacksonMaxfield** [comment]
Breaking my own rule. Can you please try the exact following:

```
conda create --name napari-aicsimageio-test python=3.9 -y
conda activate napari-aicsimageio-test
pip install --no-cache-dir --force-reinstall napari-aicsimageio
```

If it fails can I get the whole traceback?

**Comment by haesleinhuepf** [comment]
That works; on the machine where it didn't work. But it's also not installing `numcodecs` at all. @JacksonMaxfield  Can you speculate why it was trying to install that the other day?

**Comment by JacksonMaxfield** [comment]
Whole host of reasons. Env management is always the hardest thing in the world because `pip`, `conda`, `npm`, all of them like to use caching to reduce download and stuff. If it hits on an old cached download they might be incompatable now or something who knows. Whenever I have install issues where my machine is "failing to install" even though the build on the repo is passing for my Py version and platform then its time for the `--no-cache-dir --force-reinstall` to come out.

**Comment by JacksonMaxfield** [comment]
So I can close the numcodecs issue that I created too? All solved?

**Comment by haesleinhuepf** [comment]
Yes, that makes sense I guess. Thanks so much for the lightspeed response!
